'use client';

import { useCallback, useEffect, useState } from 'react';
import { Banknote, CalendarDays, CheckCircle2, Clock3, RefreshCw, Search, ShieldOff, WalletCards } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';

const rupiah = (n: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n);

type Invoice = { id:string; amount:number; dueDate:string; status:string; customer:{ id:string; customerNumber?:string; fullName:string; pppoeUsername?:string; serviceStatus?:string; packageExcel?:string; package?:{name:string}|null } };
type Data = { invoices:Invoice[]; stats:{total:number;unpaid:number;overdue:number;paid:number;revenue:number}; period:string };

export default function BillingPage() {
  const [data,setData]=useState<Data|null>(null); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{ setLoading(true); const q=new URLSearchParams(); if(search)q.set('search',search); if(status)q.set('status',status); const r=await fetch(`/api/admin/billing?${q}`); setData(await r.json()); setLoading(false); },[search,status]);
  useEffect(()=>{ const t=setTimeout(load,250); return()=>clearTimeout(t); },[load]);
  const generate=async()=>{ await fetch('/api/admin/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}); load(); };
  const action=async(id:string,a:string)=>{ await fetch(`/api/admin/billing/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:a})}); load(); };
  const cards=[['Total Tagihan',data?.stats.total??0,WalletCards],['Belum Bayar',data?.stats.unpaid??0,Clock3],['Lewat Jatuh Tempo',data?.stats.overdue??0,ShieldOff],['Sudah Bayar',data?.stats.paid??0,CheckCircle2]] as const;
  return <div className="space-y-6 p-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-gray-500">Keuangan & layanan pelanggan</p><h1 className="text-2xl font-bold text-gray-950">Billing & Isolir</h1><p className="mt-1 text-sm text-gray-500">Tagihan bulanan, jatuh tempo dan simulasi isolir MikroTik.</p></div><Button onClick={generate} className="bg-[#e10b17] hover:bg-[#c70914]"><RefreshCw className="mr-2 h-4 w-4"/>Buat Tagihan Bulan Ini</Button></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{cards.map(([t,v,I])=><div key={t} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm text-gray-500">{t}</span><I className="h-5 w-5 text-[#e10b17]"/></div><p className="mt-3 text-3xl font-bold">{v}</p></div>)}<div className="rounded-2xl border bg-[#101114] p-5 text-white shadow-sm"><div className="flex items-center justify-between"><span className="text-sm text-gray-300">Pendapatan</span><Banknote className="h-5 w-5 text-red-400"/></div><p className="mt-3 text-xl font-bold">{rupiah(data?.stats.revenue??0)}</p></div></div>
    <div className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap gap-3 border-b p-4"><div className="relative min-w-[240px] flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari pelanggan / PPPoE..." className="pl-9"/></div>{['','UNPAID','OVERDUE','PAID'].map(s=><Button key={s||'ALL'} variant={status===s?'default':'outline'} onClick={()=>setStatus(s)} className={status===s?'bg-[#e10b17] hover:bg-[#c70914]':''}>{s||'Semua'}</Button>)}</div>
      <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="p-4">Pelanggan</th><th className="p-4">Paket</th><th className="p-4">Jatuh Tempo</th><th className="p-4">Tagihan</th><th className="p-4">Pembayaran</th><th className="p-4">Layanan</th><th className="p-4 text-right">Aksi</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-10 text-center text-gray-500">Memuat billing...</td></tr>:data?.invoices.length?data.invoices.map(i=><tr key={i.id} className="border-t"><td className="p-4"><p className="font-semibold">{i.customer.fullName}</p><p className="text-xs text-gray-500">{i.customer.customerNumber||'-'} · PPPoE: {i.customer.pppoeUsername||'belum diatur'}</p></td><td className="p-4">{i.customer.package?.name||i.customer.packageExcel||'-'}</td><td className="p-4"><span className="inline-flex items-center gap-1"><CalendarDays className="h-4 w-4 text-gray-400"/>{new Date(i.dueDate).toLocaleDateString('id-ID')}</span></td><td className="p-4 font-semibold">{rupiah(i.amount)}</td><td className="p-4"><Badge variant="outline" className={i.status==='PAID'?'border-green-200 bg-green-50 text-green-700':i.status==='OVERDUE'?'border-red-200 bg-red-50 text-red-700':'border-amber-200 bg-amber-50 text-amber-700'}>{i.status}</Badge></td><td className="p-4"><Badge className={i.customer.serviceStatus==='ISOLIR'?'bg-red-600':'bg-emerald-600'}>{i.customer.serviceStatus||'ACTIVE'}</Badge></td><td className="p-4"><div className="flex justify-end gap-2">{i.status!=='PAID'&&<Button size="sm" onClick={()=>action(i.id,'PAY')} className="bg-emerald-600 hover:bg-emerald-700">Bayar</Button>}{i.customer.serviceStatus==='ISOLIR'?<Button size="sm" variant="outline" onClick={()=>action(i.id,'ACTIVATE')}>Aktifkan</Button>:<Button size="sm" variant="outline" onClick={()=>action(i.id,'ISOLATE')}>Isolir</Button>}</div></td></tr>):<tr><td colSpan={7} className="p-12 text-center text-gray-500">Belum ada tagihan. Klik “Buat Tagihan Bulan Ini”.</td></tr>}</tbody></table></div>
    </div>
  </div>;
}
