'use client';

import { useCallback, useEffect, useState } from 'react';
import { Banknote, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Loader2, RefreshCw, Search, ShieldOff, WalletCards, Wifi, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';

const rupiah=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
type NetworkSync={status:'SYNCED'|'PENDING'|'FAILED'|'UNMAPPED'|'NOT_FOUND';pppoeStatus:'ONLINE'|'OFFLINE'|'ISOLATED'|'DISABLED'|null;mode:'SIMULATION'|'LIVE'|null;message:string};
type Invoice={id:string;amount:number;dueDate:string;status:string;networkSync:NetworkSync;customer:{id:string;customerNumber?:string;fullName:string;pppoeUsername?:string;serviceStatus?:string;packageExcel?:string;package?:{name:string}|null}};
type Data={invoices:Invoice[];stats:{total:number;unpaid:number;overdue:number;paid:number;revenue:number};period:string;mikrotik:{mode:'SIMULATION'|'LIVE'|null;routerStatus:'ONLINE'|'OFFLINE';generatedAt:string|null;error:string|null};pagination:{page:number;pageSize:number;total:number;totalPages:number}};

const syncBadge=(s:NetworkSync)=>s.status==='SYNCED'?<Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700">SYNCED</Badge>:s.status==='PENDING'?<Badge variant="outline" className="border-amber-200 bg-amber-50 text-amber-700">PENDING</Badge>:s.status==='FAILED'?<Badge variant="outline" className="border-red-200 bg-red-50 text-red-700">FAILED</Badge>:s.status==='NOT_FOUND'?<Badge variant="outline" className="border-slate-200 bg-slate-50 text-slate-600">PPPoE TIDAK DITEMUKAN</Badge>:<Badge variant="outline" className="border-gray-200 bg-gray-50 text-gray-600">BELUM ADA PPPoE</Badge>;
const pppoeBadge=(s:NetworkSync['pppoeStatus'])=>!s?<span className="text-xs text-gray-400">-</span>:s==='ONLINE'?<Badge className="bg-emerald-600">ONLINE</Badge>:s==='OFFLINE'?<Badge variant="outline" className="border-gray-200 bg-gray-50 text-gray-600">OFFLINE</Badge>:<Badge className="bg-red-600">{s}</Badge>;

export default function BillingPage(){
 const[data,setData]=useState<Data|null>(null);const[search,setSearch]=useState('');const[status,setStatus]=useState('');const[page,setPage]=useState(1);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[workingId,setWorkingId]=useState<string|null>(null);const[syncing,setSyncing]=useState(false);
 const load=useCallback(async(show=true)=>{if(show&&!data)setLoading(true);else setRefreshing(true);try{const q=new URLSearchParams({page:String(page),pageSize:'50'});if(search)q.set('search',search);if(status)q.set('status',status);const r=await fetch(`/api/admin/billing?${q}`,{cache:'no-store'});if(!r.ok)throw new Error('Gagal memuat billing');setData(await r.json())}finally{setLoading(false);setRefreshing(false)}},[search,status,page,data]);
 useEffect(()=>{const t=setTimeout(()=>load(!data),250);return()=>clearTimeout(t)},[search,status,page]);
 const retrySync=async(invoiceId?:string)=>{if(invoiceId)setWorkingId(invoiceId);else setSyncing(true);try{const r=await fetch('/api/admin/billing/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(invoiceId?{invoiceId}:{limit:50})});if(!r.ok&&r.status!==503)throw new Error('Sinkronisasi gagal');await load(false)}finally{if(invoiceId)setWorkingId(null);else setSyncing(false)}};
 const generate=async()=>{setRefreshing(true);try{await fetch('/api/admin/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await load(false)}finally{setRefreshing(false)}};
 const action=async(i:Invoice,a:string)=>{setWorkingId(i.id);try{const r=await fetch(`/api/admin/billing/${i.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:a})});if(!r.ok)throw new Error('Aksi gagal');const x=await r.json();setData(c=>{if(!c)return c;const prev=i.status,next=x.status||prev,service=x.serviceStatus||i.customer.serviceStatus;const invoices=c.invoices.map(v=>v.id===i.id?{...v,status:next,customer:{...v.customer,serviceStatus:service},networkSync:{...v.networkSync,status:'PENDING' as const,message:x.networkSync?.message||v.networkSync.message}}:v);const stats={...c.stats};if(prev!=='PAID'&&next==='PAID'){if(prev==='UNPAID')stats.unpaid=Math.max(0,stats.unpaid-1);if(prev==='OVERDUE')stats.overdue=Math.max(0,stats.overdue-1);stats.paid++;stats.revenue+=i.amount}return{...c,invoices,stats}});void load(false)}finally{setWorkingId(null)}};
 const cards=[['Total Tagihan',data?.stats.total??0,WalletCards],['Belum Bayar',data?.stats.unpaid??0,Clock3],['Lewat Jatuh Tempo',data?.stats.overdue??0,ShieldOff],['Sudah Bayar',data?.stats.paid??0,CheckCircle2]] as const;
 return <div className="space-y-6 p-6">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-gray-500">Keuangan & layanan pelanggan</p><div className="flex items-center gap-3"><h1 className="text-2xl font-bold">Billing & Isolir</h1>{data?.mikrotik.mode&&<Badge variant="outline">{data.mikrotik.mode}</Badge>}</div><p className="mt-1 text-sm text-gray-500">Tagihan, layanan, PPPoE dan sinkronisasi MikroTik.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>retrySync()} disabled={syncing||refreshing}>{syncing?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 h-4 w-4"/>}Retry Sinkronisasi</Button><Button onClick={generate} disabled={refreshing} className="bg-[#e10b17] hover:bg-[#c70914]"><RefreshCw className="mr-2 h-4 w-4"/>Buat Tagihan Bulan Ini</Button></div></div>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{cards.map(([t,v,I])=><div key={t} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><span className="text-sm text-gray-500">{t}</span><I className="h-5 w-5 text-[#e10b17]"/></div><p className="mt-3 text-3xl font-bold">{v}</p></div>)}<div className="rounded-2xl border bg-[#101114] p-5 text-white"><span className="text-sm text-gray-300">Pendapatan</span><p className="mt-3 text-xl font-bold">{rupiah(data?.stats.revenue??0)}</p></div></div>
  <div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border bg-white p-4"><div className="flex gap-2 text-sm font-semibold"><Wifi className="h-4 w-4 text-emerald-600"/>Status Router</div><p className="mt-2 text-sm text-gray-500">{data?.mikrotik.routerStatus==='ONLINE'?'MikroTik terhubung':'MikroTik belum terhubung'}</p></div><div className="rounded-xl border bg-white p-4"><div className="flex gap-2 text-sm font-semibold"><RefreshCw className="h-4 w-4"/>Mode Sinkronisasi</div><p className="mt-2 text-sm text-gray-500">{data?.mikrotik.mode||'Belum tersedia'}</p></div><div className="rounded-xl border bg-white p-4"><div className="flex gap-2 text-sm font-semibold">{data?.mikrotik.error?<AlertTriangle className="h-4 w-4 text-red-600"/>:<CheckCircle2 className="h-4 w-4 text-emerald-600"/>}Kesehatan Sinkronisasi</div><p className="mt-2 text-sm text-gray-500">{data?.mikrotik.error?'Provider MikroTik bermasalah':'Provider siap digunakan'}</p></div></div>
  <div className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap gap-3 border-b p-4"><div className="relative min-w-[240px] flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400"/><Input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Cari pelanggan / PPPoE..." className="pl-9"/></div>{['','UNPAID','OVERDUE','PAID'].map(s=><Button key={s||'ALL'} variant={status===s?'default':'outline'} onClick={()=>{setStatus(s);setPage(1)}} className={status===s?'bg-[#e10b17]':''}>{s||'Semua'}</Button>)}</div>
  <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="p-4">Pelanggan</th><th className="p-4">Paket</th><th className="p-4">Jatuh Tempo</th><th className="p-4">Tagihan</th><th className="p-4">Pembayaran</th><th className="p-4">Layanan</th><th className="p-4">PPPoE</th><th className="p-4">Sinkronisasi</th><th className="p-4 text-right">Aksi</th></tr></thead><tbody>{loading?<tr><td colSpan={9} className="p-10 text-center">Memuat billing...</td></tr>:data?.invoices.length?data.invoices.map(i=><tr key={i.id} className="border-t"><td className="p-4"><p className="font-semibold">{i.customer.fullName}</p><p className="text-xs text-gray-500">{i.customer.customerNumber||'-'} · PPPoE: {i.customer.pppoeUsername||'belum diatur'}</p></td><td className="p-4">{i.customer.package?.name||i.customer.packageExcel||'-'}</td><td className="p-4"><span className="inline-flex gap-1"><CalendarDays className="h-4 w-4"/>{new Date(i.dueDate).toLocaleDateString('id-ID')}</span></td><td className="p-4 font-semibold">{rupiah(i.amount)}</td><td className="p-4"><Badge variant="outline">{i.status}</Badge></td><td className="p-4"><Badge className={i.customer.serviceStatus==='ISOLIR'?'bg-red-600':'bg-emerald-600'}>{i.customer.serviceStatus||'ACTIVE'}</Badge></td><td className="p-4">{pppoeBadge(i.networkSync.pppoeStatus)}</td><td className="p-4"><div className="space-y-1">{syncBadge(i.networkSync)}<p className="max-w-[200px] text-[11px] text-gray-400">{i.networkSync.message}</p>{(i.networkSync.status==='PENDING'||i.networkSync.status==='FAILED')&&<Button size="sm" variant="ghost" disabled={workingId===i.id} onClick={()=>retrySync(i.id)} className="h-7 px-2 text-xs"><RefreshCw className="mr-1 h-3 w-3"/>Retry</Button>}</div></td><td className="p-4"><div className="flex justify-end gap-2">{i.status!=='PAID'&&<Button size="sm" disabled={workingId===i.id} onClick={()=>action(i,'PAY')} className="bg-emerald-600">Bayar</Button>}{i.customer.serviceStatus==='ISOLIR'?<Button size="sm" variant="outline" disabled={workingId===i.id} onClick={()=>action(i,'ACTIVATE')}>Aktifkan</Button>:<Button size="sm" variant="outline" disabled={workingId===i.id} onClick={()=>action(i,'ISOLATE')}>Isolir</Button>}</div></td></tr>):<tr><td colSpan={9} className="p-12 text-center text-gray-500">Tidak ada tagihan.</td></tr>}</tbody></table></div>
  {data&&data.pagination.totalPages>1&&<div className="flex justify-between border-t p-4"><span className="text-sm text-gray-500">{data.pagination.page} / {data.pagination.totalPages}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft className="h-4 w-4"/>Sebelumnya</Button><Button variant="outline" size="sm" disabled={page>=data.pagination.totalPages} onClick={()=>setPage(p=>p+1)}>Berikutnya<ChevronRight className="h-4 w-4"/></Button></div></div>}</div>
 </div>
}
